/**
 * generatePdf.js — PDF report generator for Cambridge Hub exam results.
 * Uses jsPDF loaded dynamically from CDN.
 */

const JSPDF_CDN = "https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.5.1/jspdf.umd.min.js";

async function loadJsPDF() {
  if (window.jspdf?.jsPDF) return window.jspdf.jsPDF;
  await new Promise((resolve, reject) => {
    const script = document.createElement("script");
    script.src = JSPDF_CDN;
    script.onload = resolve;
    script.onerror = reject;
    document.head.appendChild(script);
  });
  return window.jspdf.jsPDF;
}

/** Wrap text to fit within maxWidth mm, return array of lines */
function wrapText(doc, text, maxWidth) {
  return doc.splitTextToSize(String(text ?? ""), maxWidth);
}

/** Check if we need a new page, add one if so, reset y */
function checkPage(doc, y, lineHeight, margin, pageHeight, footerFn) {
  if (y + lineHeight > pageHeight - 20) {
    footerFn(doc);
    doc.addPage();
    y = margin;
  }
  return y;
}

export async function generateExamResultsPdf({ paper, displayName, userEmail, timeTaken, answers, questions, scoreboard }) {
  const JsPDF = await loadJsPDF();
  const doc = new JsPDF({ unit: "mm", format: "a4" });

  const pageWidth = 210;
  const pageHeight = 297;
  const margin = 18;
  const contentWidth = pageWidth - margin * 2;
  const dateStr = new Date().toLocaleDateString("en-GB", { day: "2-digit", month: "short", year: "numeric" });

  const totalMarks = questions.reduce((s, q) => s + q.total_marks, 0);
  const totalEarned = Object.values(scoreboard).reduce((s, v) => s + (v ?? 0), 0);
  const totalAttempted = answers.filter(a => a.answer_text).length;
  const totalSkipped = answers.filter(a => !a.answer_text).length;
  const pct = totalMarks > 0 ? Math.round((totalEarned / totalMarks) * 100) : 0;
  const perfLabel = pct >= 80 ? "Excellent" : pct >= 60 ? "Good effort" : pct >= 40 ? "Keep practising" : "Needs more work";

  function formatTime(s) {
    const h = Math.floor(s / 3600);
    const m = Math.floor((s % 3600) / 60);
    const sec = s % 60;
    if (h > 0) return `${h}h ${m}m ${sec}s`;
    return `${m}m ${sec}s`;
  }

  let pageNum = 1;

  function drawHeader(d) {
    d.setFontSize(9);
    d.setTextColor(120, 120, 120);
    d.setFont("helvetica", "normal");
    d.text("Cambridge Hub — Feedback Report", margin, 10);
    d.text(`Paper: ${displayName || paper}`, margin, 14);
    d.text(`Date attempted: ${dateStr}`, margin + 80, 14);
    if (userEmail) d.text(`Student: ${userEmail}`, margin, 18);
    d.setDrawColor(200, 200, 200);
    d.line(margin, 21, pageWidth - margin, 21);
    d.setTextColor(30, 30, 30);
  }

  function drawFooter(d) {
    d.setFontSize(8);
    d.setTextColor(150, 150, 150);
    d.setFont("helvetica", "normal");
    d.text("Generated by Cambridge Hub — cambridgehub.base44.app", margin, pageHeight - 8);
    d.text(`Page ${pageNum}`, pageWidth - margin - 20, pageHeight - 8);
    pageNum++;
    d.setTextColor(30, 30, 30);
  }

  // ── First page ────────────────────────────────────────────────────────────
  drawHeader(doc);
  let y = 28;

  // Title
  doc.setFont("helvetica", "bold");
  doc.setFontSize(16);
  doc.text("Feedback Report", margin, y);
  y += 8;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(80, 80, 80);
  doc.text(displayName || paper, margin, y);
  y += 10;

  // ── SECTION 1: SUMMARY ───────────────────────────────────────────────────
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(30, 30, 30);
  doc.text("Summary", margin, y);
  y += 6;

  doc.setDrawColor(200, 200, 200);
  doc.line(margin, y, pageWidth - margin, y);
  y += 6;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  const summaryRows = [
    ["Total score", `${totalEarned} / ${totalMarks} marks (${pct}% — ${perfLabel})`],
    ["Time taken", formatTime(timeTaken)],
    ["Questions attempted", `${totalAttempted} of ${questions.length}`],
    ["Questions skipped", String(totalSkipped)],
  ];
  summaryRows.forEach(([label, value]) => {
    doc.setFont("helvetica", "bold");
    doc.text(label + ":", margin, y);
    doc.setFont("helvetica", "normal");
    doc.text(value, margin + 50, y);
    y += 7;
  });
  y += 4;

  // ── SECTION 2: QUESTION BREAKDOWN ────────────────────────────────────────
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(30, 30, 30);
  doc.text("Question by Question Breakdown", margin, y);
  y += 6;
  doc.setDrawColor(200, 200, 200);
  doc.line(margin, y, pageWidth - margin, y);
  y += 8;

  questions.forEach((q, i) => {
    const ans = answers[i] ?? {};
    const score = scoreboard[i] ?? (ans.answer_text ? "?" : 0);
    const feedback = ans._pdf_feedback ?? null; // populated if available
    const insight = ans._pdf_insight ?? "";
    const markScheme = q.mark_scheme ?? "";

    // Check space for question header
    y = checkPage(doc, y, 14, margin, pageHeight, drawFooter);
    if (y === margin) drawHeader(doc);

    // Question header
    doc.setFont("helvetica", "bold");
    doc.setFontSize(11);
    doc.setTextColor(30, 30, 30);
    doc.text(`Q${i + 1} — ${q.topic}`, margin, y);

    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.setTextColor(100, 100, 100);
    const scoreLabel = typeof score === "number" ? `${score} / ${q.total_marks} marks` : `? / ${q.total_marks} marks`;
    doc.text(scoreLabel, pageWidth - margin - doc.getTextWidth(scoreLabel), y);
    y += 7;

    // Question text
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(30, 30, 30);
    const qLines = wrapText(doc, q.text, contentWidth);
    qLines.forEach(line => {
      y = checkPage(doc, y, 6, margin, pageHeight, drawFooter);
      if (y === margin) drawHeader(doc);
      doc.text(line, margin, y);
      y += 5.5;
    });
    y += 2;

    // Student answer
    doc.setFont("helvetica", "bold");
    doc.setFontSize(9);
    doc.setTextColor(80, 80, 80);
    doc.text("Your answer:", margin, y);
    y += 5;
    doc.setFont("helvetica", "normal");
    doc.setTextColor(30, 30, 30);
    const ansText = ans.answer_text || "Not answered";
    const ansLines = wrapText(doc, ansText, contentWidth);
    ansLines.forEach(line => {
      y = checkPage(doc, y, 6, margin, pageHeight, drawFooter);
      if (y === margin) drawHeader(doc);
      doc.text(line, margin, y);
      y += 5.5;
    });
    y += 2;

    // Mark scheme
    doc.setFont("helvetica", "bold");
    doc.setFontSize(9);
    doc.setTextColor(80, 80, 80);
    doc.text("Mark scheme:", margin, y);
    y += 5;
    doc.setFont("helvetica", "normal");
    doc.setTextColor(60, 60, 60);
    const msLines = wrapText(doc, markScheme, contentWidth);
    msLines.forEach(line => {
      y = checkPage(doc, y, 6, margin, pageHeight, drawFooter);
      if (y === margin) drawHeader(doc);
      doc.text(line, margin, y);
      y += 5.5;
    });
    y += 2;

    // AI / examiner insight (if available in scoreboard data)
    if (insight) {
      doc.setFont("helvetica", "bold");
      doc.setFontSize(9);
      doc.setTextColor(80, 80, 80);
      doc.text("Examiner insight:", margin, y);
      y += 5;
      doc.setFont("helvetica", "normal");
      doc.setTextColor(60, 60, 60);
      const insLines = wrapText(doc, insight, contentWidth);
      insLines.forEach(line => {
        y = checkPage(doc, y, 6, margin, pageHeight, drawFooter);
        if (y === margin) drawHeader(doc);
        doc.text(line, margin, y);
        y += 5.5;
      });
      y += 2;
    }

    // Divider
    y += 2;
    doc.setDrawColor(220, 220, 220);
    y = checkPage(doc, y, 4, margin, pageHeight, drawFooter);
    if (y === margin) drawHeader(doc);
    doc.line(margin, y, pageWidth - margin, y);
    y += 8;
  });

  drawFooter(doc);

  // ── Filename & download ──────────────────────────────────────────────────
  const safeId = (displayName || paper || "report").replace(/[\/\s]/g, "_").replace(/[^a-zA-Z0-9_]/g, "");
  const datePart = new Date().toLocaleDateString("en-GB", { day: "2-digit", month: "short", year: "numeric" }).replace(/\s/g, "");
  const filename = `${safeId}_${datePart}_feedback.pdf`;

  try {
    doc.save(filename);
  } catch {
    // Mobile fallback — open in new tab
    window.open(doc.output("bloburl"), "_blank");
  }
}

/**
 * generateReviewBankPdf — exports all incorrect answers from the review bank
 * as a printable revision summary PDF.
 */
export async function generateReviewBankPdf({ questions, userEmail }) {
  const JsPDF = await loadJsPDF();
  const doc = new JsPDF({ unit: "mm", format: "a4" });

  const pageWidth = 210;
  const pageHeight = 297;
  const margin = 18;
  const contentWidth = pageWidth - margin * 2;
  const dateStr = new Date().toLocaleDateString("en-GB", { day: "2-digit", month: "short", year: "numeric" });
  let pageNum = 1;

  function drawHeader(d) {
    d.setFontSize(9);
    d.setTextColor(120, 120, 120);
    d.setFont("helvetica", "normal");
    d.text("Cambridge Hub — Incorrect Answers Revision Summary", margin, 10);
    if (userEmail) d.text(`Student: ${userEmail}`, margin, 14);
    d.text(`Generated: ${dateStr}`, pageWidth - margin - 50, 14);
    d.setDrawColor(200, 200, 200);
    d.line(margin, 17, pageWidth - margin, 17);
    d.setTextColor(30, 30, 30);
  }

  function drawFooter(d) {
    d.setFontSize(8);
    d.setTextColor(150, 150, 150);
    d.setFont("helvetica", "normal");
    d.text("Generated by Cambridge Hub — cambridgehub.base44.app", margin, pageHeight - 8);
    d.text(`Page ${pageNum}`, pageWidth - margin - 20, pageHeight - 8);
    pageNum++;
    d.setTextColor(30, 30, 30);
  }

  drawHeader(doc);
  let y = 24;

  // Title
  doc.setFont("helvetica", "bold");
  doc.setFontSize(16);
  doc.setTextColor(30, 30, 30);
  doc.text("Incorrect Answers — Revision Summary", margin, y);
  y += 7;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(80, 80, 80);
  doc.text(`${questions.length} question${questions.length !== 1 ? "s" : ""} to revise`, margin, y);
  y += 10;

  doc.setDrawColor(200, 200, 200);
  doc.line(margin, y, pageWidth - margin, y);
  y += 8;

  questions.forEach((q, i) => {
    // Section header
    y = checkPage(doc, y, 14, margin, pageHeight, drawFooter);
    if (y === margin) drawHeader(doc);

    // Topic + score badge
    doc.setFont("helvetica", "bold");
    doc.setFontSize(11);
    doc.setTextColor(30, 30, 30);
    doc.text(`${i + 1}. ${q.topic ?? "Unknown Topic"}`, margin, y);

    if (q.first_attempt_score != null && q.total_marks != null) {
      doc.setFont("helvetica", "normal");
      doc.setFontSize(9);
      doc.setTextColor(160, 60, 60);
      const scoreStr = `${q.first_attempt_score} / ${q.total_marks} marks`;
      doc.text(scoreStr, pageWidth - margin - doc.getTextWidth(scoreStr), y);
    }
    y += 7;

    // Question text
    if (q.question_text) {
      doc.setFont("helvetica", "normal");
      doc.setFontSize(10);
      doc.setTextColor(30, 30, 30);
      const qLines = wrapText(doc, q.question_text, contentWidth);
      qLines.forEach(line => {
        y = checkPage(doc, y, 6, margin, pageHeight, drawFooter);
        if (y === margin) drawHeader(doc);
        doc.text(line, margin, y);
        y += 5.5;
      });
      y += 3;
    }

    // Mark scheme
    if (q.mark_scheme) {
      doc.setFont("helvetica", "bold");
      doc.setFontSize(9);
      doc.setTextColor(30, 100, 60);
      doc.text("Mark Scheme:", margin, y);
      y += 5;
      doc.setFont("helvetica", "normal");
      doc.setTextColor(40, 80, 50);
      const msLines = wrapText(doc, q.mark_scheme, contentWidth);
      msLines.forEach(line => {
        y = checkPage(doc, y, 6, margin, pageHeight, drawFooter);
        if (y === margin) drawHeader(doc);
        doc.text(line, margin, y);
        y += 5.5;
      });
      y += 3;
    }

    // Explanation / insight
    if (q.explanation) {
      doc.setFont("helvetica", "bold");
      doc.setFontSize(9);
      doc.setTextColor(60, 60, 120);
      doc.text("Explanation:", margin, y);
      y += 5;
      doc.setFont("helvetica", "normal");
      doc.setTextColor(50, 50, 100);
      const expLines = wrapText(doc, q.explanation, contentWidth);
      expLines.forEach(line => {
        y = checkPage(doc, y, 6, margin, pageHeight, drawFooter);
        if (y === margin) drawHeader(doc);
        doc.text(line, margin, y);
        y += 5.5;
      });
      y += 3;
    }

    // Divider
    y += 2;
    doc.setDrawColor(220, 220, 220);
    y = checkPage(doc, y, 4, margin, pageHeight, drawFooter);
    if (y === margin) drawHeader(doc);
    doc.line(margin, y, pageWidth - margin, y);
    y += 8;
  });

  drawFooter(doc);

  const datePart = dateStr.replace(/\s/g, "");
  const filename = `ReviewBank_${datePart}.pdf`;
  try {
    doc.save(filename);
  } catch {
    window.open(doc.output("bloburl"), "_blank");
  }
}