/**
 * p1StarPdf.js — Teacher Review PDF for starred questions.
 * Includes a 'What the teacher said' lined box after each question.
 */

const JSPDF_CDN = "https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.5.1/jspdf.umd.min.js";

async function loadJsPDF() {
  if (window.jspdf?.jsPDF) return window.jspdf.jsPDF;
  await new Promise((resolve, reject) => {
    const script = document.createElement("script");
    script.src = JSPDF_CDN;
    script.onload = resolve;
    script.onerror = reject;
    document.head.appendChild(script);
  });
  return window.jspdf.jsPDF;
}

function fmtDate(iso) {
  if (!iso) return null;
  try {
    return new Date(iso).toLocaleDateString("en-GB", {
      day: "2-digit", month: "short", year: "numeric",
      hour: "2-digit", minute: "2-digit",
    });
  } catch { return null; }
}

export async function generateStarredPdf({ paperId, displayName, userEmail, starredQuestions }) {
  const JsPDF = await loadJsPDF();
  const doc = new JsPDF({ unit: "mm", format: "a4" });

  const pageW = 210;
  const pageH = 297;
  const margin = 18;
  const contentW = pageW - margin * 2;  // 174 mm
  const LINE_H = 5.5;
  const RULE_SPACING = 7;  // mm between ruled lines in teacher response box
  const NUM_RULES = 5;     // number of ruled lines for teacher response
  const dateStr = new Date().toLocaleDateString("en-GB", {
    day: "2-digit", month: "short", year: "numeric",
  });
  let pageNum = 1;
  let y = margin;

  // Always set font+size before splitTextToSize so metrics are correct
  function wrapAt(text, fontSize, fontStyle, maxW) {
    doc.setFont("helvetica", fontStyle ?? "normal");
    doc.setFontSize(fontSize);
    return doc.splitTextToSize(String(text ?? ""), maxW);
  }

  function drawHeader() {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.setTextColor(130, 130, 130);
    doc.text("Cambridge Hub — Teacher Review", margin, 10);
    if (displayName ?? paperId) doc.text(`Paper: ${displayName ?? paperId}`, margin, 14);
    doc.text(`Generated: ${dateStr}`, pageW - margin, 14, { align: "right" });
    if (userEmail) doc.text(`Student: ${userEmail}`, margin, 18);
    doc.setDrawColor(200, 200, 200);
    doc.setLineWidth(0.4);
    doc.line(margin, 21, pageW - margin, 21);
    doc.setTextColor(30, 30, 30);
  }

  function drawFooter() {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text("Generated by Cambridge Hub", margin, pageH - 8);
    doc.text(`Page ${pageNum}`, pageW - margin, pageH - 8, { align: "right" });
    pageNum++;
    doc.setTextColor(30, 30, 30);
  }

  function checkSpace(needed) {
    if (y + needed > pageH - 22) {
      drawFooter();
      doc.addPage();
      y = margin + 10;
      drawHeader();
    }
  }

  /**
   * Draw the "What the teacher said" box.
   * Cream background + "TEACHER RESPONSE" label + NUM_RULES ruled lines.
   */
  function drawTeacherResponseBox() {
    const boxH = 12 + NUM_RULES * RULE_SPACING + 4; // label row + rules + bottom padding
    checkSpace(boxH + 6);

    // Box background
    doc.setFillColor(255, 253, 240);
    doc.setDrawColor(180, 150, 40);
    doc.setLineWidth(0.5);
    doc.roundedRect(margin, y, contentW, boxH, 3, 3, "FD");

    // Label
    doc.setFont("helvetica", "bold");
    doc.setFontSize(8);
    doc.setTextColor(130, 90, 0);
    doc.text("TEACHER RESPONSE", margin + 5, y + 7);

    // Ruled lines for writing
    doc.setDrawColor(200, 180, 100);
    doc.setLineWidth(0.3);
    for (let i = 0; i < NUM_RULES; i++) {
      const lineY = y + 12 + i * RULE_SPACING;
      doc.line(margin + 5, lineY, margin + contentW - 5, lineY);
    }

    y += boxH + 8;
  }

  // ── Cover page ─────────────────────────────────────────────────────────────
  drawHeader();
  y = 30;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  doc.setTextColor(20, 20, 20);
  doc.text("Teacher Review", margin, y);
  y += 8;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(80, 80, 80);
  doc.text("Questions flagged during practice for teacher consultation", margin, y);
  y += 10;

  doc.setDrawColor(200, 200, 200);
  doc.setLineWidth(0.5);
  doc.line(margin, y, pageW - margin, y);
  y += 8;

  const entries = Object.values(starredQuestions).sort((a, b) => a.questionNumber - b.questionNumber);

  doc.setFont("helvetica", "italic");
  doc.setFontSize(9);
  doc.setTextColor(120, 120, 120);
  doc.text(`${entries.length} question${entries.length !== 1 ? "s" : ""} starred`, margin, y);
  y += 10;

  drawFooter();

  // ── Per-question entries ───────────────────────────────────────────────────
  entries.forEach((entry, ei) => {

    checkSpace(50);

    // ── Question header card ────────────────────────────────────────────────
    const starredFmt = fmtDate(entry.starredAt);
    // 3 rows: Question N / Topic / Starred on
    const headerH = starredFmt ? 30 : 22;

    doc.setFillColor(232, 240, 255);
    doc.setDrawColor(170, 200, 240);
    doc.setLineWidth(0.5);
    doc.roundedRect(margin, y, contentW, headerH, 3, 3, "FD");

    // "Question N"
    doc.setFont("helvetica", "bold");
    doc.setFontSize(13);
    doc.setTextColor(15, 40, 100);
    doc.text(`Question ${entry.questionNumber}`, margin + 5, y + 9);

    // Topic
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.setTextColor(60, 90, 150);
    doc.text(entry.topic ?? "", margin + 5, y + 17);

    // Starred on date (plain text, no emoji — jsPDF doesn't support emoji)
    if (starredFmt) {
      doc.setFont("helvetica", "italic");
      doc.setFontSize(8);
      doc.setTextColor(100, 130, 180);
      doc.text(`Starred on: ${starredFmt}`, margin + 5, y + 25);
    }

    doc.setTextColor(30, 30, 30);
    y += headerH + 6;

    // ── Question text ───────────────────────────────────────────────────────
    if (entry.questionText) {
      const qLines = wrapAt(entry.questionText, 10, "normal", contentW);
      checkSpace(qLines.length * LINE_H + 6);
      doc.setFont("helvetica", "normal");
      doc.setFontSize(10);
      doc.setTextColor(30, 30, 30);
      qLines.forEach(line => {
        checkSpace(LINE_H + 1);
        doc.text(line, margin, y);
        y += LINE_H;
      });
      y += 5;
    }

    // ── Options ─────────────────────────────────────────────────────────────
    if (entry.options) {
      checkSpace(10);
      doc.setFont("helvetica", "bold");
      doc.setFontSize(9);
      doc.setTextColor(70, 70, 70);
      doc.text("Options", margin, y);
      y += 5;

      ["A", "B", "C", "D"].forEach(k => {
        const isCorrect = k === entry.correctAnswer;
        const optLines = wrapAt(`${k}.   ${entry.options[k] ?? ""}`, 10, isCorrect ? "bold" : "normal", contentW - 6);
        checkSpace(optLines.length * 5.2 + 3);
        if (isCorrect) {
          doc.setFont("helvetica", "bold");
          doc.setTextColor(22, 120, 60);
        } else {
          doc.setFont("helvetica", "normal");
          doc.setTextColor(65, 65, 65);
        }
        doc.setFontSize(10);
        optLines.forEach(line => {
          checkSpace(6);
          doc.text(line, margin + 3, y);
          y += 5.2;
        });
      });

      y += 4;
      doc.setFont("helvetica", "bold");
      doc.setFontSize(10);
      doc.setTextColor(22, 120, 60);
      doc.text(`Correct answer: ${entry.correctAnswer}`, margin, y);
      y += 8;
      doc.setTextColor(30, 30, 30);
    }

    // ── AI Feedback ─────────────────────────────────────────────────────────
    const fb = entry.feedback;
    if (fb) {
      const sections = [
        { title: "Exam Takeaway",               content: fb.pulse_layer_1,          r: 22,  g: 120, b: 60  },
        { title: "Cambridge Insight",           content: fb.cambridge_insight,       r: 37,  g: 99,  b: 200 },
        { title: "Step 1 — Concept Tested",    content: fb.step1_system,            r: 60,  g: 60,  b: 60  },
        { title: "Step 2 — Key Phrases",       content: fb.step2_phrase_breakdown,  r: 60,  g: 60,  b: 60  },
        { title: "Step 3 — The Tipping Point", content: fb.step3_tipping_point,     r: 60,  g: 60,  b: 60  },
      ].filter(s => s.content?.trim());

      if (sections.length > 0) {
        checkSpace(14);

        doc.setFont("helvetica", "bold");
        doc.setFontSize(9.5);
        doc.setTextColor(40, 40, 40);
        doc.text("AI Feedback", margin, y);
        y += 2;
        doc.setDrawColor(200, 200, 200);
        doc.setLineWidth(0.3);
        doc.line(margin, y + 1, pageW - margin, y + 1);
        y += 6;

        sections.forEach(s => {
          const lines = wrapAt(s.content, 10, "normal", contentW - 4);
          checkSpace(lines.length * LINE_H + 10);

          doc.setFont("helvetica", "bold");
          doc.setFontSize(8.5);
          doc.setTextColor(s.r, s.g, s.b);
          doc.text(s.title, margin, y);
          y += 5;

          doc.setFont("helvetica", "normal");
          doc.setFontSize(10);
          doc.setTextColor(40, 40, 40);
          lines.forEach(line => {
            checkSpace(LINE_H + 1);
            doc.text(line, margin + 3, y);
            y += LINE_H;
          });
          y += 4;
        });
      }
    }

    // ── Student's question for teacher ──────────────────────────────────────
    if (entry.teacherQuestion?.trim()) {
      const tqLines = wrapAt(entry.teacherQuestion, 10, "bolditalic", contentW - 10);
      const tqBoxH = tqLines.length * LINE_H + 14;
      checkSpace(tqBoxH + 4);

      y += 2;
      doc.setFillColor(255, 252, 235);
      doc.setDrawColor(200, 160, 20);
      doc.setLineWidth(0.6);
      doc.roundedRect(margin, y, contentW, tqBoxH, 3, 3, "FD");

      doc.setFont("helvetica", "bold");
      doc.setFontSize(8.5);
      doc.setTextColor(140, 100, 0);
      doc.text("Student's Question", margin + 5, y + 6);

      doc.setFont("helvetica", "bolditalic");
      doc.setFontSize(10);
      doc.setTextColor(80, 55, 0);
      tqLines.forEach((line, li) => {
        doc.text(line, margin + 5, y + 11 + li * LINE_H);
      });
      y += tqBoxH + 6;
    }

    // ── Teacher Response box ─────────────────────────────────────────────────
    drawTeacherResponseBox();

    // ── Divider ─────────────────────────────────────────────────────────────
    if (ei < entries.length - 1) {
      checkSpace(10);
      y += 4;
      doc.setDrawColor(200, 200, 200);
      doc.setLineWidth(0.4);
      doc.line(margin, y, pageW - margin, y);
      y += 14;
    }
  });

  drawFooter();

  const safeId = (displayName ?? paperId ?? "review")
    .replace(/[\/\s]/g, "_").replace(/[^a-zA-Z0-9_]/g, "");
  const filename = `TeacherReview_${safeId}_${dateStr.replace(/\s/g, "")}.pdf`;
  try { doc.save(filename); } catch { window.open(doc.output("bloburl"), "_blank"); }
}