/**
 * p1StarPdf.js — Teacher Review PDF for starred questions.
 * Clean section headings, generous spacing, teacher question bold+italic at bottom.
 */

const JSPDF_CDN = "https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.5.1/jspdf.umd.min.js";

async function loadJsPDF() {
  if (window.jspdf?.jsPDF) return window.jspdf.jsPDF;
  await new Promise((resolve, reject) => {
    const script = document.createElement("script");
    script.src = JSPDF_CDN;
    script.onload = resolve;
    script.onerror = reject;
    document.head.appendChild(script);
  });
  return window.jspdf.jsPDF;
}

function fmtStarredDate(iso) {
  if (!iso) return null;
  try {
    return new Date(iso).toLocaleDateString("en-GB", {
      weekday: "short", day: "2-digit", month: "short", year: "numeric",
      hour: "2-digit", minute: "2-digit",
    });
  } catch {
    return null;
  }
}

/** Wrap text to fit within maxWidth mm, return array of lines */
function wrapText(doc, text, maxWidth) {
  return doc.splitTextToSize(String(text ?? ""), maxWidth);
}

/** Check if we need a new page, add one if so, reset y */
function checkPage(doc, y, lineHeight, margin, pageHeight, footerFn) {
  if (y + lineHeight > pageHeight - 20) {
    footerFn(doc);
    doc.addPage();
    y = margin;
  }
  return y;
}

export async function generateStarredPdf({ paperId, displayName, userEmail, starredQuestions }) {
  const JsPDF = await loadJsPDF();
  const doc = new JsPDF({ unit: "mm", format: "a4" });

  const pageWidth = 210;
  const pageHeight = 297;
  const margin = 18;
  const contentWidth = pageWidth - margin * 2;
  const dateStr = new Date().toLocaleDateString("en-GB", { day: "2-digit", month: "short", year: "numeric" });

  const LINE_H = 5.5;
  let pageNum = 1;

  function drawHeader(d) {
    d.setFontSize(9);
    d.setTextColor(120, 120, 120);
    d.setFont("helvetica", "normal");
    d.text("Cambridge Hub — Teacher Review", margin, 10);
    if (displayName ?? paperId) d.text(`Paper: ${displayName ?? paperId}`, margin, 14);
    d.text(`Date generated: ${dateStr}`, margin + 80, 14);
    if (userEmail) d.text(`Student: ${userEmail}`, margin, 18);
    d.setDrawColor(200, 200, 200);
    d.line(margin, 21, pageWidth - margin, 21);
    d.setTextColor(30, 30, 30);
  }

  function drawFooter(d) {
    d.setFontSize(8);
    d.setTextColor(150, 150, 150);
    d.setFont("helvetica", "normal");
    d.text("Generated by Cambridge Hub — cambridgehub.base44.app", margin, pageHeight - 8);
    d.text(`Page ${pageNum}`, pageWidth - margin - 20, pageHeight - 8);
    pageNum++;
    d.setTextColor(30, 30, 30);
  }

  // ── First page ─────────────────────────────────────────────────────────────
  drawHeader(doc);
  let y = 28;

  // Title
  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.text("Teacher Review", margin, y);
  y += 8;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(80, 80, 80);
  doc.text("Questions starred during practice — for teacher consultation", margin, y);
  y += 10;

  const entries = Object.values(starredQuestions).sort((a, b) => a.questionNumber - b.questionNumber);
  doc.setFont("helvetica", "italic");
  doc.setFontSize(9);
  doc.setTextColor(120, 120, 120);
  doc.text(`${entries.length} question${entries.length !== 1 ? "s" : ""} starred`, margin, y);
  y += 10;

  doc.setDrawColor(200, 200, 200);
  doc.setLineWidth(0.5);
  doc.line(margin, y, pageWidth - margin, y);
  y += 8;

  // ── Per-question entries ───────────────────────────────────────────────────
  entries.forEach((entry, ei) => {
    // Check space for the header block
    y = checkPage(doc, y, 36, margin, pageHeight, drawFooter);
    if (y === margin) drawHeader(doc);

    // ── Question header card ────────────────────────────────────────────────
    const headerH = 28;
    doc.setFillColor(232, 240, 255);
    doc.setDrawColor(170, 200, 240);
    doc.setLineWidth(0.5);
    doc.roundedRect(margin, y, contentWidth, headerH, 3, 3, "FD");

    // "Question N" — large bold
    doc.setFont("helvetica", "bold");
    doc.setFontSize(13);
    doc.setTextColor(15, 40, 100);
    doc.text(`Question ${entry.questionNumber}`, margin + 5, y + 9);

    // Topic — smaller, below
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.setTextColor(60, 90, 150);
    doc.text(entry.topic ?? "", margin + 5, y + 17);

    // Starred date — right-aligned inside the card
    const starredFmt = fmtStarredDate(entry.starredAt);
    if (starredFmt) {
      doc.setFont("helvetica", "italic");
      doc.setFontSize(8);
      doc.setTextColor(100, 130, 180);
      doc.text(`⭐ Starred: ${starredFmt}`, pageWidth - margin - 5, y + 9, { align: "right" });
    }

    doc.setTextColor(30, 30, 30);
    y += headerH + 5;

    // ── Question text ───────────────────────────────────────────────────────
    if (entry.questionText) {
      const qLines = wrapText(doc, entry.questionText, contentWidth);
      checkPage(doc, y, qLines.length * LINE_H + 4, margin, pageHeight, drawFooter);
      doc.setFont("helvetica", "normal");
      doc.setFontSize(10);
      doc.setTextColor(30, 30, 30);
      qLines.forEach(line => {
        y = checkPage(doc, y, LINE_H + 1, margin, pageHeight, drawFooter);
        if (y === margin) drawHeader(doc);
        doc.text(line, margin, y);
        y += LINE_H;
      });
      y += 5;
    }

    // ── Correct answer + options ────────────────────────────────────────────
    if (entry.options) {
      checkPage(doc, y, 8, margin, pageHeight, drawFooter);
      doc.setFont("helvetica", "bold");
      doc.setFontSize(8.5);
      doc.setTextColor(70, 70, 70);
      doc.text("Options", margin, y);
      y += 5;

      ["A", "B", "C", "D"].forEach(k => {
        const isCorrect = k === entry.correctAnswer;
        const optLines = wrapText(doc, `${k}.  ${entry.options[k] ?? ""}`, contentWidth - 4);
        y = checkPage(doc, y, optLines.length * 5 + 2, margin, pageHeight, drawFooter);
        if (isCorrect) {
          doc.setFont("helvetica", "bold");
          doc.setTextColor(22, 120, 60);
        } else {
          doc.setFont("helvetica", "normal");
          doc.setTextColor(70, 70, 70);
        }
        doc.setFontSize(10);
        optLines.forEach(line => {
          doc.text(line, margin + 3, y);
          y += 5;
        });
      });

      y += 3;
      doc.setFont("helvetica", "bold");
      doc.setFontSize(10);
      doc.setTextColor(22, 120, 60);
      doc.text(`Correct answer: ${entry.correctAnswer}`, margin, y);
      y += 8;
      doc.setTextColor(30, 30, 30);
    }

    // ── AI Feedback ─────────────────────────────────────────────────────────
    const fb = entry.feedback;
    if (fb) {
      const sections = [
        { title: "Exam Takeaway", content: fb.pulse_layer_1, r: 22, g: 120, b: 60 },
        { title: "Cambridge Insight", content: fb.cambridge_insight, r: 37, g: 99, b: 200 },
        { title: "Step 1 — System & Objective", content: fb.step1_system, r: 60, g: 60, b: 60 },
        { title: "Step 2 — Phrase Breakdown", content: fb.step2_phrase_breakdown, r: 60, g: 60, b: 60 },
        { title: "Step 3 — The Tipping Point", content: fb.step3_tipping_point, r: 60, g: 60, b: 60 },
      ].filter(s => s.content);

      if (sections.length > 0) {
        checkPage(doc, y, 14, margin, pageHeight, drawFooter);
        if (y === margin) drawHeader(doc);

        doc.setFont("helvetica", "bold");
        doc.setFontSize(9.5);
        doc.setTextColor(40, 40, 40);
        doc.text("AI Feedback", margin, y);
        y += 2;
        doc.setDrawColor(200, 200, 200);
        doc.setLineWidth(0.3);
        doc.line(margin, y + 1, pageWidth - margin, y + 1);
        y += 6;

        sections.forEach(s => {
          const lines = wrapText(doc, s.content, contentWidth - 4);
          checkPage(doc, y, lines.length * LINE_H + 10, margin, pageHeight, drawFooter);
          if (y === margin) drawHeader(doc);

          doc.setFont("helvetica", "bold");
          doc.setFontSize(8.5);
          doc.setTextColor(s.r, s.g, s.b);
          doc.text(s.title, margin, y);
          y += 5;

          doc.setFont("helvetica", "normal");
          doc.setFontSize(10);
          doc.setTextColor(40, 40, 40);
          lines.forEach(line => {
            y = checkPage(doc, y, LINE_H + 1, margin, pageHeight, drawFooter);
            if (y === margin) drawHeader(doc);
            doc.text(line, margin + 3, y);
            y += LINE_H;
          });
          y += 4;
        });
      }
    }

    // ── Teacher's question ──────────────────────────────────────────────────
    if (entry.teacherQuestion?.trim()) {
      const tqLines = wrapText(doc, entry.teacherQuestion, contentWidth - 10);
      const tqBoxH = tqLines.length * LINE_H + 14;
      checkPage(doc, y, tqBoxH + 4, margin, pageHeight, drawFooter);
      if (y === margin) drawHeader(doc);

      y += 2;
      doc.setFillColor(255, 252, 235);
      doc.setDrawColor(200, 160, 20);
      doc.setLineWidth(0.6);
      doc.roundedRect(margin, y, contentWidth, tqBoxH, 3, 3, "FD");

      doc.setFont("helvetica", "bold");
      doc.setFontSize(8.5);
      doc.setTextColor(140, 100, 0);
      doc.text("Question for Teacher", margin + 5, y + 6);

      doc.setFont("helvetica", "bolditalic");
      doc.setFontSize(10);
      doc.setTextColor(80, 55, 0);
      tqLines.forEach((line, li) => {
        doc.text(line, margin + 5, y + 11 + li * LINE_H);
      });
      y += tqBoxH + 6;
    }

    // ── Divider ─────────────────────────────────────────────────────────────
    if (ei < entries.length - 1) {
      checkPage(doc, y, 10, margin, pageHeight, drawFooter);
      if (y === margin) drawHeader(doc);
      y += 4;
      doc.setDrawColor(200, 200, 200);
      doc.setLineWidth(0.4);
      doc.line(margin, y, pageWidth - margin, y);
      y += 14;
    }
  });

  drawFooter(doc);

  const safeId = (displayName ?? paperId ?? "review")
    .replace(/[\/\s]/g, "_")
    .replace(/[^a-zA-Z0-9_]/g, "");
  const filename = `TeacherReview_${safeId}_${dateStr.replace(/\s/g, "")}.pdf`;
  try { doc.save(filename); } catch { window.open(doc.output("bloburl"), "_blank"); }
}