const JSPDF_CDN = "https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.5.1/jspdf.umd.min.js";

async function loadJsPDF() {
  if (window.jspdf?.jsPDF) return window.jspdf.jsPDF;
  await new Promise((resolve, reject) => {
    const script = document.createElement("script");
    script.src = JSPDF_CDN;
    script.onload = resolve;
    script.onerror = reject;
    document.head.appendChild(script);
  });
  return window.jspdf.jsPDF;
}

function fmtDate(iso) {
  if (!iso) return null;
  try {
    return new Date(iso).toLocaleDateString("en-GB", {
      day: "2-digit", month: "short", year: "numeric",
      hour: "2-digit", minute: "2-digit",
    });
  } catch { return null; }
}

export async function generateStarredPdf({ paperId, displayName, userEmail, starredQuestions }) {
  const JsPDF = await loadJsPDF();
  const doc = new JsPDF({ unit: "mm", format: "a4" });

  const pageW = 210;
  const pageH = 297;
  const margin = 18;
  const contentW = pageW - margin * 2;
  const LINE_H = 5.5;
  const dateStr = new Date().toLocaleDateString("en-GB", {
    day: "2-digit", month: "short", year: "numeric",
  });
  let pageNum = 1;
  let y = margin;

  function wrapAt(text, fontSize, fontStyle, maxW) {
    doc.setFont("helvetica", fontStyle ?? "normal");
    doc.setFontSize(fontSize);
    return doc.splitTextToSize(String(text ?? ""), maxW);
  }

  function drawHeader() {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.setTextColor(130, 130, 130);
    doc.text("Cambridge Hub — Teacher Review", margin, 10);
    if (displayName ?? paperId) doc.text(`Paper: ${displayName ?? paperId}`, margin, 14);
    doc.text(`Generated: ${dateStr}`, pageW - margin, 14, { align: "right" });
    if (userEmail) doc.text(`Student: ${userEmail}`, margin, 18);
    doc.setDrawColor(200, 200, 200);
    doc.setLineWidth(0.4);
    doc.line(margin, 21, pageW - margin, 21);
    doc.setTextColor(30, 30, 30);
  }

  function drawFooter() {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text("Generated by Cambridge Hub", margin, pageH - 8);
    doc.text(`Page ${pageNum}`, pageW - margin, pageH - 8, { align: "right" });
    pageNum++;
    doc.setTextColor(30, 30, 30);
  }

  function checkSpace(needed) {
    if (y + needed > pageH - 22) {
      drawFooter();
      doc.addPage();
      y = margin + 10;
      drawHeader();
    }
  }

  /**
   * Draw "What the teacher said" box.
   * If teacherResponse is filled in: render as text inside the box.
   * If empty: draw 5 ruled blank lines for handwriting.
   */
  function drawTeacherResponseBox(teacherResponse) {
    const hasResponse = teacherResponse?.trim();
    const NUM_RULES = 5;
    const RULE_SPACING = 8;
    const labelH = 10;
    const bottomPad = 6;

    let boxH;
    let responseLines = [];
    if (hasResponse) {
      responseLines = wrapAt(teacherResponse.trim(), 10, "normal", contentW - 10);
      boxH = labelH + responseLines.length * LINE_H + bottomPad + 4;
    } else {
      boxH = labelH + NUM_RULES * RULE_SPACING + bottomPad;
    }

    checkSpace(boxH + 8);

    // Background
    doc.setFillColor(255, 251, 230);
    doc.rect(margin, y, contentW, boxH, "F");

    // Border
    doc.setDrawColor(190, 150, 30);
    doc.setLineWidth(0.8);
    doc.rect(margin, y, contentW, boxH, "S");

    // Left accent bar
    doc.setFillColor(190, 150, 30);
    doc.rect(margin, y, 3, boxH, "F");

    // Label
    doc.setFont("helvetica", "bold");
    doc.setFontSize(9);
    doc.setTextColor(120, 80, 0);
    doc.text("WHAT THE TEACHER SAID", margin + 7, y + 7);

    // Separator under label
    doc.setDrawColor(210, 175, 90);
    doc.setLineWidth(0.4);
    doc.line(margin + 3, y + labelH, margin + contentW, y + labelH);

    if (hasResponse) {
      // Render typed teacher response
      doc.setFont("helvetica", "normal");
      doc.setFontSize(10);
      doc.setTextColor(60, 40, 0);
      responseLines.forEach((line, i) => {
        doc.text(line, margin + 7, y + labelH + 5 + i * LINE_H);
      });
    } else {
      // Blank ruled lines for handwriting
      doc.setDrawColor(210, 190, 130);
      doc.setLineWidth(0.3);
      for (let i = 0; i < NUM_RULES; i++) {
        const lineY = y + labelH + 4 + i * RULE_SPACING;
        doc.line(margin + 7, lineY, margin + contentW - 5, lineY);
      }
    }

    doc.setTextColor(30, 30, 30);
    y += boxH + 10;
  }

  // ── Cover page ──────────────────────────────────────────────────────────────
  drawHeader();
  y = 30;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  doc.setTextColor(20, 20, 20);
  doc.text("Teacher Review", margin, y);
  y += 8;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(80, 80, 80);
  doc.text("Questions flagged during practice for teacher consultation", margin, y);
  y += 10;

  doc.setDrawColor(200, 200, 200);
  doc.setLineWidth(0.5);
  doc.line(margin, y, pageW - margin, y);
  y += 8;

  const entries = Object.values(starredQuestions).sort((a, b) => a.questionNumber - b.questionNumber);

  doc.setFont("helvetica", "italic");
  doc.setFontSize(9);
  doc.setTextColor(120, 120, 120);
  doc.text(`${entries.length} question${entries.length !== 1 ? "s" : ""} starred`, margin, y);
  y += 10;

  drawFooter();

  // ── Per-question entries ────────────────────────────────────────────────────
  entries.forEach((entry, ei) => {

    checkSpace(50);

    // Question header card
    const starredFmt = fmtDate(entry.starredAt);
    const headerH = starredFmt ? 30 : 22;

    doc.setFillColor(232, 240, 255);
    doc.setDrawColor(170, 200, 240);
    doc.setLineWidth(0.5);
    doc.rect(margin, y, contentW, headerH, "F");
    doc.rect(margin, y, contentW, headerH, "S");

    doc.setFont("helvetica", "bold");
    doc.setFontSize(13);
    doc.setTextColor(15, 40, 100);
    doc.text(`Question ${entry.questionNumber}`, margin + 5, y + 9);

    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.setTextColor(60, 90, 150);
    doc.text(entry.topic ?? "", margin + 5, y + 17);

    if (starredFmt) {
      doc.setFont("helvetica", "italic");
      doc.setFontSize(8);
      doc.setTextColor(100, 130, 180);
      doc.text(`Starred on: ${starredFmt}`, margin + 5, y + 25);
    }

    doc.setTextColor(30, 30, 30);
    y += headerH + 6;

    // Question text
    if (entry.questionText) {
      const qLines = wrapAt(entry.questionText, 10, "normal", contentW);
      checkSpace(qLines.length * LINE_H + 6);
      doc.setFont("helvetica", "normal");
      doc.setFontSize(10);
      doc.setTextColor(30, 30, 30);
      qLines.forEach(line => {
        checkSpace(LINE_H + 1);
        doc.text(line, margin, y);
        y += LINE_H;
      });
      y += 5;
    }

    // AI takeaway
    if (entry.feedback?.pulse_layer_1) {
      const tLines = wrapAt(entry.feedback.pulse_layer_1, 9, "italic", contentW - 6);
      checkSpace(tLines.length * 5 + 10);
      doc.setFillColor(232, 248, 236);
      const tBoxH = tLines.length * 5 + 10;
      doc.rect(margin, y, contentW, tBoxH, "F");
      doc.setFont("helvetica", "bold");
      doc.setFontSize(8);
      doc.setTextColor(10, 80, 40);
      doc.text("EXAM TAKEAWAY", margin + 5, y + 6);
      doc.setFont("helvetica", "italic");
      doc.setFontSize(9);
      doc.setTextColor(20, 80, 40);
      tLines.forEach((line, i) => { doc.text(line, margin + 5, y + 11 + i * 5); });
      y += tBoxH + 4;
      doc.setTextColor(30, 30, 30);
    }

    // Student's question for teacher
    if (entry.teacherQuestion?.trim()) {
      const tqLines = wrapAt(entry.teacherQuestion, 10, "bolditalic", contentW - 10);
      const tqBoxH = tqLines.length * LINE_H + 14;
      checkSpace(tqBoxH + 4);

      y += 2;
      doc.setFillColor(255, 252, 235);
      doc.setDrawColor(200, 160, 20);
      doc.setLineWidth(0.6);
      doc.rect(margin, y, contentW, tqBoxH, "F");
      doc.rect(margin, y, contentW, tqBoxH, "S");

      doc.setFont("helvetica", "bold");
      doc.setFontSize(8.5);
      doc.setTextColor(140, 100, 0);
      doc.text("STUDENT'S QUESTION FOR TEACHER", margin + 5, y + 6);

      doc.setFont("helvetica", "bolditalic");
      doc.setFontSize(10);
      doc.setTextColor(80, 55, 0);
      tqLines.forEach((line, li) => {
        doc.text(line, margin + 5, y + 11 + li * LINE_H);
      });
      y += tqBoxH + 6;
    }

    // ── TEACHER RESPONSE BOX ────────────────────────────────────────────────
    y += 2;
    drawTeacherResponseBox(entry.teacherResponse ?? "");

    // Divider
    if (ei < entries.length - 1) {
      checkSpace(10);
      y += 4;
      doc.setDrawColor(200, 200, 200);
      doc.setLineWidth(0.4);
      doc.line(margin, y, pageW - margin, y);
      y += 14;
    }
  });

  drawFooter();

  const safeId = (displayName ?? paperId ?? "review")
    .replace(/[\/\s]/g, "_").replace(/[^a-zA-Z0-9_]/g, "");
  const filename = `TeacherReview_${safeId}_${dateStr.replace(/\s/g, "")}.pdf`;
  try { doc.save(filename); } catch { window.open(doc.output("bloburl"), "_blank"); }
}