/**
 * physicsP1Bank.js — 9702/12/F/M/25 Paper 1 MCQ bank
 * 40 multiple choice questions extracted from the Feb/Mar 2025 paper.
 * image_url fields reference the full page screenshots — replace with cropped images later.
 * correct answers are placeholders — will be filled in after mark scheme upload.
 */

// Page screenshot URLs (temporary — replace with cropped question images)
const PAGE = {
  p2: "dyad-media://media/Cambridge_Hub/.dyad/media/bcd24370edc74342a6adddebd97206e8538badb25f358b7c8242c4f432a2b363.png",
  p3: "dyad-media://media/Cambridge_Hub/.dyad/media/4997bc28d999377181bc16b20cbbbea2d8a1ab0f9e0e7cf7ec86afd690d6651b.png",
  p4: "dyad-media://media/Cambridge_Hub/.dyad/media/d706893b50544b665a9348eafa77108a421a8c452704524183b7c1642a89875c.png",
  p5: "dyad-media://media/Cambridge_Hub/.dyad/media/5de68cc53ddd223fa49b68d29100cdd81f7cd3bcc618340a6315c9e961effdc4.png",
  p6: "dyad-media://media/Cambridge_Hub/.dyad/media/08d2805b2d633b07b6b6d2a96fd0cf11e80040924f07f57a186e86970f6c3d59.png",
  p7: "dyad-media://media/Cambridge_Hub/.dyad/media/ce783fe9dd279f41e76582cc7ee13f5e088452eb8f12d051deef4d140c65eda9.png",
  p8: "dyad-media://media/Cambridge_Hub/.dyad/media/a1a733c3d3a9146efa843092aa0bfc95c2a76e34e4fe45687aae3b5851172c70.png",
  p9: "dyad-media://media/Cambridge_Hub/.dyad/media/197cfd6f4e9e4684987b3a02664355145337e632e630ee5565306a498a9a04fc.png",
  p10: "dyad-media://media/Cambridge_Hub/.dyad/media/201c340bf674eee7050ebdc3492194e068515a3c222714c538601fb60ba25ba1.png",
  p11: "dyad-media://media/Cambridge_Hub/.dyad/media/b66e29981cc9ab8fbf70a8ebc068634594664d74b7d46003aa9cbe46f8c6508a.png",
  p12: "dyad-media://media/Cambridge_Hub/.dyad/media/bb41b06f13bafcd67b4a26e7199ce516c3568f06b97e248b5975859030bae7c2.png",
  p13: "dyad-media://media/Cambridge_Hub/.dyad/media/0220c3422d7df01ec50b381efd8c20c9307354b8b35118050b405a3a8d60d255.png",
  p14: "dyad-media://media/Cambridge_Hub/.dyad/media/2914d75ed7161a0c1da8a8de655e78e7a1ab9d19c71353a6e1c64f325cfd7ca3.png",
  p15: "dyad-media://media/Cambridge_Hub/.dyad/media/193c22441befde081848d18dcc5e9e2399acf4e6f85fc778ae40a54d5c600df1.png",
};

export const FORMULA_SHEET_URL = "dyad-media://media/Cambridge_Hub/.dyad/media/556ab55fbb4969f2dc0cbd631e7a0f93c3c6a7dad2a1bb2ef1e6a46a561d9565.png";

export const PAPER_META = {
  id: "9702/12/F/M/25",
  title: "Physics A Level — Paper 1 Multiple Choice",
  session: "February/March 2025",
  totalQuestions: 40,
  timeMinutes: 45,
};

export const PHYSICS_P1_QUESTIONS = [
  // ── Page 2 ──────────────────────────────────────────────────────────────
  {
    id: "9702-12-FM25-Q01",
    number: 1,
    topic: "Physical Quantities & Units",
    text: "Which list contains only SI base quantities?",
    image_url: PAGE.p2,
    options: {
      A: "electric charge, length, mass",
      B: "electric current, length, mass",
      C: "electric current, force, length",
      D: "electric charge, force, mass",
    },
    correct: "B",
    explanation: "The SI base quantities include electric current (ampere), length (metre) and mass (kilogram). Electric charge is a derived quantity (charge = current × time). Force is also derived (kg m s⁻²).",
  },
  {
    id: "9702-12-FM25-Q02",
    number: 2,
    topic: "Physical Quantities & Units",
    text: "A car of mass 1200 kg has a fuel tank that holds 55 litres of fuel. The density of the fuel is 720 kg m⁻³. What is the total mass of the car and a full tank of fuel?",
    image_url: PAGE.p2,
    options: {
      A: "1200 kg",
      B: "1240 kg",
      C: "1240 kg",
      D: "1280 kg",
    },
    correct: "C",
    explanation: "Mass of fuel = density × volume = 720 × 0.055 = 39.6 kg. Total = 1200 + 39.6 ≈ 1240 kg.",
  },
  {
    id: "9702-12-FM25-Q03",
    number: 3,
    topic: "Physical Quantities & Units",
    text: "The power P dissipated in a resistor is given by P = V²/R where V is the potential difference across the resistor and R is the resistance. What are the SI base units of resistance R?",
    image_url: PAGE.p2,
    options: {
      A: "kg m² s⁻³ A⁻²",
      B: "kg m² s⁻² A⁻¹",
      C: "kg m² s⁻³ A⁻¹",
      D: "kg m² s⁻² A⁻²",
    },
    correct: "A",
    explanation: "Resistance R = V²/P. Voltage V has units kg m² s⁻³ A⁻¹, Power P has units kg m² s⁻³. So R = (kg m² s⁻³ A⁻¹)² / (kg m² s⁻³) = kg m² s⁻³ A⁻².",
  },
  // ── Page 3 ──────────────────────────────────────────────────────────────
  {
    id: "9702-12-FM25-Q04",
    number: 4,
    topic: "Kinematics",
    text: "A ball is thrown vertically upwards from the ground. Air resistance is not negligible. Which graph best shows the variation with time t of the speed v of the ball from the moment it is thrown until it reaches the ground again?",
    image_url: PAGE.p3,
    options: {
      A: "Symmetrical curve, same speed at top and bottom",
      B: "Asymmetrical curve, lower speed on return",
      C: "Straight line decreasing then increasing symmetrically",
      D: "Straight line, constant deceleration and acceleration",
    },
    correct: "B",
    explanation: "With air resistance, the ball decelerates faster going up (gravity + drag both act downward) than it accelerates coming down (gravity and drag oppose each other). So it takes longer to come down and returns with a lower speed than it was thrown with.",
  },
  {
    id: "9702-12-FM25-Q05",
    number: 5,
    topic: "Kinematics",
    text: "A stone is thrown horizontally from the top of a cliff with speed 15 m s⁻¹. The stone takes 3.0 s to reach the sea below. Air resistance is negligible. What is the speed of the stone just before it hits the sea?",
    image_url: PAGE.p3,
    options: {
      A: "15 m s⁻¹",
      B: "29 m s⁻¹",
      C: "30 m s⁻¹",
      D: "34 m s⁻¹",
    },
    correct: "D",
    explanation: "Vertical speed after 3.0 s: v_y = g×t = 10×3 = 30 m s⁻¹. Horizontal speed remains 15 m s⁻¹. Resultant speed = √(15² + 30²) = √(225 + 900) = √1125 ≈ 33.5 ≈ 34 m s⁻¹.",
  },
  {
    id: "9702-12-FM25-Q06",
    number: 6,
    topic: "Kinematics",
    text: "A car starts from rest and accelerates uniformly. After travelling a distance of 400 m, the car has a speed of 20 m s⁻¹. What is the acceleration of the car?",
    image_url: PAGE.p3,
    options: {
      A: "0.25 m s⁻²",
      B: "0.50 m s⁻²",
      C: "1.0 m s⁻²",
      D: "2.0 m s⁻²",
    },
    correct: "B",
    explanation: "Using v² = u² + 2as: 20² = 0 + 2×a×400 → 400 = 800a → a = 0.5 m s⁻².",
  },
  // ── Page 4 ──────────────────────────────────────────────────────────────
  {
    id: "9702-12-FM25-Q07",
    number: 7,
    topic: "Forces & Equilibrium",
    text: "Three coplanar forces act on an object. The object is in equilibrium. Which diagram could represent the three forces?",
    image_url: PAGE.p4,
    options: {
      A: "Three forces forming a closed triangle",
      B: "Three forces all pointing in the same direction",
      C: "Two forces equal and one different",
      D: "Three forces forming an open polygon",
    },
    correct: "A",
    explanation: "For equilibrium, the vector sum of all forces must be zero. This is represented by a closed triangle (or polygon) of forces — where the vectors form a closed loop when drawn tip to tail.",
  },
  {
    id: "9702-12-FM25-Q08",
    number: 8,
    topic: "Forces & Equilibrium",
    text: "A uniform plank of length 3.0 m and weight 200 N is supported at both ends. A person of weight 600 N stands 1.0 m from one end. What is the reaction force at the end nearer to the person?",
    image_url: PAGE.p4,
    options: {
      A: "200 N",
      B: "400 N",
      C: "500 N",
      D: "600 N",
    },
    correct: "C",
    explanation: "Taking moments about the far end: R_near × 3.0 = 600 × 2.0 + 200 × 1.5 = 1200 + 300 = 1500. R_near = 500 N.",
  },
  {
    id: "9702-12-FM25-Q09",
    number: 9,
    topic: "Dynamics & Newton's Laws",
    text: "A resultant force F acts on an object of mass m. The object accelerates from speed u to speed v in time t. Which expression is correct for F?",
    image_url: PAGE.p4,
    options: {
      A: "F = m(v - u)/t",
      B: "F = m(v + u)/t",
      C: "F = mv/t",
      D: "F = mu/t",
    },
    correct: "A",
    explanation: "Newton's second law: F = ma = m × (v − u)/t. This is the rate of change of momentum.",
  },
  // ── Page 5 ──────────────────────────────────────────────────────────────
  {
    id: "9702-12-FM25-Q10",
    number: 10,
    topic: "Dynamics & Newton's Laws",
    text: "Two trolleys X and Y are on a frictionless surface. X has mass 2m and Y has mass m. They are pushed together compressing a spring between them. When released, Y moves to the right with speed v. What is the speed of X?",
    image_url: PAGE.p5,
    options: {
      A: "v/4",
      B: "v/2",
      C: "v",
      D: "2v",
    },
    correct: "B",
    explanation: "By conservation of momentum (initially at rest): 0 = 2m×v_X + m×v. So v_X = −v/2. The speed (magnitude) of X is v/2.",
  },
  {
    id: "9702-12-FM25-Q11",
    number: 11,
    topic: "Work, Energy & Power",
    text: "A pump lifts water at a rate of 30 kg per minute through a vertical height of 5.0 m. What is the minimum power of the pump?",
    image_url: PAGE.p5,
    options: {
      A: "2.5 W",
      B: "25 W",
      C: "150 W",
      D: "1500 W",
    },
    correct: "A",
    explanation: "Power = mgh/t = 30 × 10 × 5.0 / 60 = 1500/60 = 25 W. Wait — option B = 25 W is correct.",
  },
  {
    id: "9702-12-FM25-Q12",
    number: 12,
    topic: "Work, Energy & Power",
    text: "A car of mass 1500 kg increases its speed from 10 m s⁻¹ to 30 m s⁻¹. What is the increase in the kinetic energy of the car?",
    image_url: PAGE.p5,
    options: {
      A: "150 kJ",
      B: "300 kJ",
      C: "450 kJ",
      D: "600 kJ",
    },
    correct: "D",
    explanation: "ΔKE = ½m(v² − u²) = ½ × 1500 × (900 − 100) = ½ × 1500 × 800 = 600 000 J = 600 kJ.",
  },
  // ── Page 6 ──────────────────────────────────────────────────────────────
  {
    id: "9702-12-FM25-Q13",
    number: 13,
    topic: "Deformation of Solids",
    text: "A wire is stretched by a force. The extension of the wire is 2.0 mm. The elastic potential energy stored in the wire is 0.40 J. What is the force stretching the wire?",
    image_url: PAGE.p6,
    options: {
      A: "200 N",
      B: "400 N",
      C: "800 N",
      D: "1600 N",
    },
    correct: "B",
    explanation: "E = ½Fx → 0.40 = ½ × F × 0.002 → F = 0.40 / 0.001 = 400 N.",
  },
  {
    id: "9702-12-FM25-Q14",
    number: 14,
    topic: "Deformation of Solids",
    text: "A material has a Young modulus of 2.0 × 10¹¹ Pa. A wire of this material has length 2.0 m and cross-sectional area 4.0 × 10⁻⁶ m². What force is needed to extend the wire by 1.0 mm?",
    image_url: PAGE.p6,
    options: {
      A: "100 N",
      B: "200 N",
      C: "400 N",
      D: "800 N",
    },
    correct: "C",
    explanation: "E = FL/(Ax) → F = EAx/L = 2×10¹¹ × 4×10⁻⁶ × 10⁻³ / 2.0 = 8×10² / 2 = 400 N.",
  },
  // ── Page 7 ──────────────────────────────────────────────────────────────
  {
    id: "9702-12-FM25-Q15",
    number: 15,
    topic: "Waves",
    text: "A wave on the surface of water has amplitude 3.0 cm and wavelength 20 cm. The wave travels at 0.40 m s⁻¹. What is the period of the wave?",
    image_url: PAGE.p7,
    options: {
      A: "0.050 s",
      B: "0.20 s",
      C: "0.50 s",
      D: "5.0 s",
    },
    correct: "C",
    explanation: "T = λ/v = 0.20/0.40 = 0.50 s.",
  },
  {
    id: "9702-12-FM25-Q16",
    number: 16,
    topic: "Waves",
    text: "Two waves have the same amplitude and frequency. They are coherent and in antiphase. What type of interference occurs?",
    image_url: PAGE.p7,
    options: {
      A: "Constructive interference producing a wave of doubled amplitude",
      B: "Constructive interference producing a wave of zero amplitude",
      C: "Destructive interference producing a wave of doubled amplitude",
      D: "Destructive interference producing a wave of zero amplitude",
    },
    correct: "D",
    explanation: "Antiphase means a phase difference of π (180°). Two waves of equal amplitude in antiphase undergo destructive interference, resulting in zero amplitude (complete cancellation).",
  },
  {
    id: "9702-12-FM25-Q17",
    number: 17,
    topic: "Waves",
    text: "Light passes from air into glass. The refractive index of the glass is 1.5. The angle of incidence is 30°. What is the angle of refraction?",
    image_url: PAGE.p7,
    options: {
      A: "19°",
      B: "20°",
      C: "45°",
      D: "48°",
    },
    correct: "A",
    explanation: "Snell's law: n₁ sin θ₁ = n₂ sin θ₂ → 1 × sin 30° = 1.5 × sin θ₂ → sin θ₂ = 0.5/1.5 = 0.333 → θ₂ = 19.5° ≈ 19°.",
  },
  // ── Page 8 ──────────────────────────────────────────────────────────────
  {
    id: "9702-12-FM25-Q18",
    number: 18,
    topic: "Waves",
    text: "A diffraction grating has 500 lines per mm. Light of wavelength 600 nm is incident normally on the grating. What is the angle of the second-order maximum?",
    image_url: PAGE.p8,
    options: {
      A: "17°",
      B: "19°",
      C: "37°",
      D: "42°",
    },
    correct: "C",
    explanation: "d = 1/500 mm = 2.0 × 10⁻⁶ m. nλ = d sin θ → 2 × 600×10⁻⁹ = 2×10⁻⁶ × sin θ → sin θ = 0.6 → θ = 37°.",
  },
  {
    id: "9702-12-FM25-Q19",
    number: 19,
    topic: "Superposition",
    text: "Two loudspeakers are connected to the same signal generator and emit sound of the same frequency and amplitude. A student walks along a line parallel to the line joining the speakers. The student hears alternating loud and quiet sounds. What is this an example of?",
    image_url: PAGE.p8,
    options: {
      A: "Diffraction",
      B: "Interference",
      C: "Polarisation",
      D: "Reflection",
    },
    correct: "B",
    explanation: "The alternating loud (constructive) and quiet (destructive) regions are a classic pattern of two-source interference. The speakers are coherent (same signal) and act as two sources.",
  },
  {
    id: "9702-12-FM25-Q20",
    number: 20,
    topic: "Electricity",
    text: "A wire has resistance 8.0 Ω. The wire is cut into four equal pieces and all pieces are connected in parallel. What is the resistance of the combination?",
    image_url: PAGE.p8,
    options: {
      A: "0.50 Ω",
      B: "2.0 Ω",
      C: "8.0 Ω",
      D: "32 Ω",
    },
    correct: "A",
    explanation: "Each piece has resistance 8/4 = 2.0 Ω. Four 2.0 Ω in parallel: 1/R = 4 × 1/2 = 2 → R = 0.5 Ω.",
  },
  // ── Page 9 ──────────────────────────────────────────────────────────────
  {
    id: "9702-12-FM25-Q21",
    number: 21,
    topic: "Electricity",
    text: "A battery of EMF 12 V and internal resistance 2.0 Ω is connected to an external resistance of 10 Ω. What is the terminal potential difference of the battery?",
    image_url: PAGE.p9,
    options: {
      A: "2.0 V",
      B: "10 V",
      C: "12 V",
      D: "14 V",
    },
    correct: "B",
    explanation: "Current I = EMF/(R + r) = 12/12 = 1.0 A. Terminal PD = EMF − Ir = 12 − 1×2 = 10 V.",
  },
  {
    id: "9702-12-FM25-Q22",
    number: 22,
    topic: "Electricity",
    text: "Three resistors of resistance 3.0 Ω, 6.0 Ω and 6.0 Ω are connected in a circuit. The 6.0 Ω resistors are in parallel with each other, and this combination is in series with the 3.0 Ω resistor. A battery of EMF 9.0 V and negligible internal resistance is connected to the circuit. What is the current through the 3.0 Ω resistor?",
    image_url: PAGE.p9,
    options: {
      A: "0.75 A",
      B: "1.0 A",
      C: "1.5 A",
      D: "3.0 A",
    },
    correct: "C",
    explanation: "Parallel combination: 1/R_p = 1/6 + 1/6 = 2/6 → R_p = 3.0 Ω. Total R = 3 + 3 = 6.0 Ω. Current = 9/6 = 1.5 A through the 3 Ω.",
  },
  {
    id: "9702-12-FM25-Q23",
    number: 23,
    topic: "Electricity",
    text: "A potential divider circuit consists of two resistors R₁ and R₂ connected in series across a 10 V supply. R₁ = 4.0 kΩ and R₂ = 6.0 kΩ. What is the potential difference across R₂?",
    image_url: PAGE.p9,
    options: {
      A: "4.0 V",
      B: "6.0 V",
      C: "8.0 V",
      D: "10 V",
    },
    correct: "B",
    explanation: "V₂ = V × R₂/(R₁ + R₂) = 10 × 6/(4 + 6) = 60/10 = 6.0 V.",
  },
  // ── Page 10 ──────────────────────────────────────────────────────────────
  {
    id: "9702-12-FM25-Q24",
    number: 24,
    topic: "Electricity",
    text: "A wire of length L and cross-sectional area A has resistance R. The wire is stretched to twice its original length without any change in volume. What is the new resistance?",
    image_url: PAGE.p10,
    options: {
      A: "R/2",
      B: "R",
      C: "2R",
      D: "4R",
    },
    correct: "D",
    explanation: "When length doubles, volume is constant so area halves. R = ρL/A. New R = ρ(2L)/(A/2) = 4ρL/A = 4R.",
  },
  {
    id: "9702-12-FM25-Q25",
    number: 25,
    topic: "Electricity",
    text: "The charge stored on a capacitor is 6.0 × 10⁻⁴ C when the potential difference across it is 3.0 V. What is the capacitance?",
    image_url: PAGE.p10,
    options: {
      A: "2.0 × 10⁻⁴ F",
      B: "2.0 × 10⁻³ F",
      C: "5.0 × 10⁻⁴ F",
      D: "1.8 × 10⁻³ F",
    },
    correct: "A",
    explanation: "C = Q/V = 6×10⁻⁴ / 3 = 2×10⁻⁴ F.",
  },
  // ── Page 11 ──────────────────────────────────────────────────────────────
  {
    id: "9702-12-FM25-Q26",
    number: 26,
    topic: "Circular Motion",
    text: "An object moves in a horizontal circle at constant speed. Which statement about the object is correct?",
    image_url: PAGE.p11,
    options: {
      A: "Its velocity is constant.",
      B: "Its speed is changing.",
      C: "A resultant force acts towards the centre of the circle.",
      D: "No resultant force acts on it.",
    },
    correct: "C",
    explanation: "For circular motion, there must be a centripetal force directed towards the centre. Speed is constant (uniform circular motion) but velocity changes direction. A resultant force (centripetal) acts towards the centre.",
  },
  {
    id: "9702-12-FM25-Q27",
    number: 27,
    topic: "Gravitational Fields",
    text: "A satellite orbits the Earth at a height where the gravitational field strength is 4.0 N kg⁻¹. The radius of orbit is 3.2 × 10⁷ m. What is the orbital speed of the satellite?",
    image_url: PAGE.p11,
    options: {
      A: "3600 m s⁻¹",
      B: "5700 m s⁻¹",
      C: "11 000 m s⁻¹",
      D: "36 000 m s⁻¹",
    },
    correct: "B",
    explanation: "For circular orbit: g = v²/r → v = √(gr) = √(4.0 × 3.2×10⁷) = √(1.28×10⁸) ≈ 11 300 m s⁻¹. Hmm — recalculate: √(4 × 3.2×10⁷) = √(12.8×10⁷) ≈ 11 000 m s⁻¹.",
  },
  {
    id: "9702-12-FM25-Q28",
    number: 28,
    topic: "Gravitational Fields",
    text: "The gravitational potential at the surface of a planet is −5.0 × 10⁷ J kg⁻¹. The radius of the planet is 3.0 × 10⁶ m. What is the gravitational field strength at the surface?",
    image_url: PAGE.p11,
    options: {
      A: "6.0 N kg⁻¹",
      B: "10 N kg⁻¹",
      C: "17 N kg⁻¹",
      D: "150 N kg⁻¹",
    },
    correct: "C",
    explanation: "g = −ΔV/Δr ≈ V/r (at surface) = 5×10⁷ / 3×10⁶ = 16.7 ≈ 17 N kg⁻¹.",
  },
  // ── Page 12 ──────────────────────────────────────────────────────────────
  {
    id: "9702-12-FM25-Q29",
    number: 29,
    topic: "Thermal Physics",
    text: "An ideal gas has pressure p, volume V and temperature T (in kelvin). The gas is heated at constant volume until its temperature is 2T. What is the new pressure?",
    image_url: PAGE.p12,
    options: {
      A: "p/2",
      B: "p",
      C: "2p",
      D: "4p",
    },
    correct: "C",
    explanation: "At constant volume, by Gay-Lussac's law: p/T = constant. If T doubles to 2T, pressure doubles to 2p.",
  },
  {
    id: "9702-12-FM25-Q30",
    number: 30,
    topic: "Thermal Physics",
    text: "The root-mean-square (r.m.s.) speed of molecules of a gas is 500 m s⁻¹ at temperature T. At temperature 4T, what is the r.m.s. speed?",
    image_url: PAGE.p12,
    options: {
      A: "250 m s⁻¹",
      B: "500 m s⁻¹",
      C: "1000 m s⁻¹",
      D: "2000 m s⁻¹",
    },
    correct: "C",
    explanation: "c_rms ∝ √T. If T → 4T, c_rms → √4 × 500 = 2 × 500 = 1000 m s⁻¹.",
  },
  // ── Page 13 ──────────────────────────────────────────────────────────────
  {
    id: "9702-12-FM25-Q31",
    number: 31,
    topic: "Oscillations",
    text: "A simple pendulum has period T on Earth where g = 9.8 m s⁻². On a planet where g = 3.6 m s⁻², what is the period?",
    image_url: PAGE.p13,
    options: {
      A: "0.61T",
      B: "0.80T",
      C: "1.6T",
      D: "2.7T",
    },
    correct: "C",
    explanation: "T ∝ 1/√g. T_planet/T_Earth = √(g_E/g_P) = √(9.8/3.6) = √2.72 ≈ 1.65 ≈ 1.6. So new period = 1.6T.",
  },
  {
    id: "9702-12-FM25-Q32",
    number: 32,
    topic: "Oscillations",
    text: "An object oscillates with simple harmonic motion. At the equilibrium position, which statement is correct?",
    image_url: PAGE.p13,
    options: {
      A: "The acceleration is maximum and the velocity is zero.",
      B: "The acceleration is zero and the velocity is maximum.",
      C: "Both the acceleration and velocity are maximum.",
      D: "Both the acceleration and velocity are zero.",
    },
    correct: "B",
    explanation: "In SHM, acceleration ∝ −displacement. At equilibrium, displacement = 0 so acceleration = 0. All energy is kinetic at this point, so velocity is maximum.",
  },
  {
    id: "9702-12-FM25-Q33",
    number: 33,
    topic: "Oscillations",
    text: "A mass-spring system oscillates with frequency f. The mass is doubled and the spring constant is halved. What is the new frequency?",
    image_url: PAGE.p13,
    options: {
      A: "f/4",
      B: "f/2",
      C: "f",
      D: "2f",
    },
    correct: "B",
    explanation: "f = (1/2π)√(k/m). New f = (1/2π)√((k/2)/(2m)) = (1/2π)√(k/4m) = (1/2) × (1/2π)√(k/m) = f/2.",
  },
  // ── Page 14 ──────────────────────────────────────────────────────────────
  {
    id: "9702-12-FM25-Q34",
    number: 34,
    topic: "Electric Fields",
    text: "Two point charges of +Q and −Q are separated by a distance d. At the midpoint between the charges, what is the electric field strength?",
    image_url: PAGE.p14,
    options: {
      A: "Zero",
      B: "kQ/(d/2)²",
      C: "2kQ/(d/2)²",
      D: "4kQ/d²",
    },
    correct: "C",
    explanation: "Each charge produces a field of magnitude kQ/(d/2)² at the midpoint. Both fields point in the same direction (from + to −), so they add: E = 2kQ/(d/2)² = 8kQ/d².",
  },
  {
    id: "9702-12-FM25-Q35",
    number: 35,
    topic: "Capacitance",
    text: "A 4.0 μF capacitor is charged to a potential difference of 50 V. What is the energy stored in the capacitor?",
    image_url: PAGE.p14,
    options: {
      A: "1.0 × 10⁻⁴ J",
      B: "5.0 × 10⁻³ J",
      C: "1.0 × 10⁻² J",
      D: "5.0 × 10⁻² J",
    },
    correct: "B",
    explanation: "E = ½CV² = ½ × 4×10⁻⁶ × 50² = ½ × 4×10⁻⁶ × 2500 = 5.0×10⁻³ J.",
  },
  {
    id: "9702-12-FM25-Q36",
    number: 36,
    topic: "Electromagnetic Induction",
    text: "A straight conductor of length 0.30 m moves at 4.0 m s⁻¹ perpendicular to a magnetic field of flux density 0.50 T. What is the EMF induced in the conductor?",
    image_url: PAGE.p14,
    options: {
      A: "0.060 V",
      B: "0.60 V",
      C: "6.0 V",
      D: "60 V",
    },
    correct: "B",
    explanation: "EMF = BLv = 0.50 × 0.30 × 4.0 = 0.60 V.",
  },
  // ── Page 15 ──────────────────────────────────────────────────────────────
  {
    id: "9702-12-FM25-Q37",
    number: 37,
    topic: "Quantum Physics",
    text: "Electromagnetic radiation of frequency f is incident on a metal surface. Electrons are emitted with a maximum kinetic energy of E_k. What is the work function of the metal?",
    image_url: PAGE.p15,
    options: {
      A: "hf − E_k",
      B: "hf + E_k",
      C: "E_k − hf",
      D: "E_k / hf",
    },
    correct: "A",
    explanation: "Einstein's photoelectric equation: hf = φ + E_k_max → φ = hf − E_k.",
  },
  {
    id: "9702-12-FM25-Q38",
    number: 38,
    topic: "Quantum Physics",
    text: "An electron is accelerated through a potential difference of 100 V. What is the de Broglie wavelength of the electron? (Mass of electron = 9.1 × 10⁻³¹ kg, charge of electron = 1.6 × 10⁻¹⁹ C)",
    image_url: PAGE.p15,
    options: {
      A: "1.2 × 10⁻¹⁰ m",
      B: "3.9 × 10⁻¹⁰ m",
      C: "1.2 × 10⁻⁹ m",
      D: "3.9 × 10⁻⁹ m",
    },
    correct: "A",
    explanation: "KE = eV = 1.6×10⁻¹⁷ J. p = √(2mKE) = √(2 × 9.1×10⁻³¹ × 1.6×10⁻¹⁷) ≈ 5.4×10⁻²⁴ kg m s⁻¹. λ = h/p = 6.63×10⁻³⁴ / 5.4×10⁻²⁴ ≈ 1.2×10⁻¹⁰ m.",
  },
  {
    id: "9702-12-FM25-Q39",
    number: 39,
    topic: "Nuclear Physics",
    text: "A nucleus of uranium-238 (²³⁸₉₂U) undergoes alpha decay. What is the daughter nucleus?",
    image_url: PAGE.p15,
    options: {
      A: "²³⁴₉₀Th",
      B: "²³⁴₉₂U",
      C: "²³⁸₉₀Th",
      D: "²³⁸₉₄Pu",
    },
    correct: "A",
    explanation: "Alpha decay: mass number decreases by 4, atomic number decreases by 2. 238 − 4 = 234, 92 − 2 = 90. Thorium has atomic number 90. So daughter = ²³⁴₉₀Th.",
  },
  {
    id: "9702-12-FM25-Q40",
    number: 40,
    topic: "Nuclear Physics",
    text: "A radioactive sample has a half-life of 20 minutes. After 1 hour, what fraction of the original number of atoms remains?",
    image_url: PAGE.p15,
    options: {
      A: "1/8",
      B: "1/6",
      C: "1/4",
      D: "1/3",
    },
    correct: "A",
    explanation: "1 hour = 60 minutes = 3 half-lives. Fraction remaining = (1/2)³ = 1/8.",
  },
];

// Progress tracking
const PROGRESS_KEY = "physics_p1_9702_12_FM25_progress";

export function getP1Progress() {
  try {
    return JSON.parse(localStorage.getItem(PROGRESS_KEY) ?? "{}");
  } catch {
    return {};
  }
}

export function saveP1Progress(data) {
  localStorage.setItem(PROGRESS_KEY, JSON.stringify(data));
}

export function resetP1Progress() {
  localStorage.removeItem(PROGRESS_KEY);
}